# TODO: PRITIFY
version: "3.8"
services:
  # producer:
  #   build: publisher
  #   ports:
  #     - ${PUBLISHER_PORT}:80
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./publisher:/usr/src/app
  #   networks:
  #     - nats-streaming-net
  #   stdin_open: true #check
  #   tty: true #check
  # consumer:
  #   build: consumer
  #   ports:
  #     - ${CONSUMER_PORT}:80
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./consumer:/user/src/app
  #   stdin_open: true #check
  #   tty: true # check
  nats-streaming:
    image: nats-streaming:0.25-alpine
    command:
      - --cluster_id
      - ${NATS_STAN_CLUSTER_ID}
    volumes:
      - ./.mnt/nats-stan:/var/lib/nats-stan/data
    networks:
      - nats-streaming-net
    ports:
      - ${NATS_STAN_STORE_PORT}:4222
      - ${NATS_STAN_MONITORING_PORT}:8222
    restart: unless-stopped
  postgres:
    image: postgres:16-alpine
    hostname: ${POSTGRES_HOST}
    ports:
      - 5432:${POSTGRES_PORT}      
    env_file:
      - .env
    volumes:
      - ./.mnt/pg:/var/lib/pg/data
    networks:
      - pg-net
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    env_file:
      - .env
    volumes:
      - ./.mnt/pgadmin:/var/lib/pgadmin/data
    networks:
      - pg-net
    restart: unless-stopped
networks:
  pg-net:
    driver: bridge
  nats-streaming-net:
    driver: bridge
