definitions:
  domain.Delivery:
    properties:
      address:
        example: Ploshad Mira 15
        type: string
      city:
        example: Kiryat Mozkin
        type: string
      email:
        description: 'TODO: validate'
        example: test@gmail.com
        type: string
      name:
        example: Test Testov
        type: string
      phone:
        description: 'TODO: validate'
        example: "+9720000000"
        type: string
      region:
        example: Kraiot
        type: string
      zip:
        description: 'TODO: validate'
        example: "2639809"
        type: string
    type: object
  domain.Item:
    properties:
      brand:
        example: Vivienne Sabo
        type: string
      chrt_id:
        example: 9934930
        type: integer
      name:
        example: Mascaras
        type: string
      nm_id:
        example: 2389212
        type: integer
      order_uid:
        example: b563feb7b2b84b6test
        type: string
      price:
        example: 453
        type: number
      rid:
        example: ab4219087a764ae0btest
        type: string
      sale:
        example: 30
        type: number
      size:
        example: "0"
        type: string
      status:
        example: 202
        type: integer
      total_price:
        example: 317
        type: number
      track_number:
        description: get it from order
        example: WBILMTESTTRACK
        type: string
    type: object
  domain.Payment:
    properties:
      amount:
        example: 1817
        type: number
      bank:
        example: alpha
        type: string
      currency:
        type: string
      custom_fee:
        example: 0
        type: number
      delivery_cost:
        example: 1500
        type: number
      goods_total:
        example: 317
        type: number
      payment_dt:
        example: "1637907727"
        type: string
      provider:
        example: wbpay
        type: string
      request_id:
        type: string
      transaction:
        example: b563feb7b2b84b6test
        type: string
    type: object
  httpHandler.ErrorResponse:
    properties:
      message:
        example: Error message
        type: string
    type: object
  httpHandler.OrderResponse:
    properties:
      customer_id:
        example: test
        type: string
      date_created:
        example: "2021-11-26T06:22:19Z"
        type: string
      delivery:
        $ref: '#/definitions/domain.Delivery'
      delivery_service:
        example: meest
        type: string
      entry:
        example: WBIL
        type: string
      internal_signature:
        type: string
      items:
        items:
          $ref: '#/definitions/domain.Item'
        type: array
      locale:
        example: en
        type: string
      oof_shard:
        example: "1"
        type: string
      order_uid:
        description: 19 sumbols uuid? // maybe type of uuid
        example: b563feb7b2b84b6test
        type: string
      payment:
        $ref: '#/definitions/domain.Payment'
      shardkey:
        example: "9"
        type: string
      sm_id:
        example: 99
        type: integer
      track_number:
        description: 14 sub
        example: WBILMTESTTRACK
        type: string
    required:
    - delivery
    - items
    - order_uid
    - payment
    type: object
info:
  contact: {}
paths:
  /v1/order/{uid}:
    get:
      consumes:
      - application/json
      description: Get order with related entities by order_uid
      parameters:
      - description: Order UID
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpHandler.OrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpHandler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httpHandler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpHandler.ErrorResponse'
      summary: Get an order by ID
      tags:
      - Order
swagger: "2.0"
