name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    strategy:
      matrix:
        go: ['1.21']
        os: [macos-latest, windows-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: golangci-lint-consumer
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: consumer
      - name: golangci-lint-publisher
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: publisher